const eyeColors = [
    "black", // 0
    "lightbluegreen", // 1
    "darkblue", // 2
    "brown", // 3
    "darkerbrown", // 4
    "lightbrown", // 5
    "blue", // 6
    "lightblue", // 7
    "pink", // 8
    "yellow", // 9
    "purple", // 10
    "black", // 11
    "darkgreen", // 12
    "lightbrown", // 13
    "yellowblackpattern", // 14
    "lightspiralpattern", // 15
    "shinyred", // 16
    "shinybluehalfred", // 17
    "halfblackhalflightblue", // 18
    "whiteredperimeter", // 19
    "greensnake", // 20
    "redsnake", // 21
    "darkbluesnake", // 22
    "darkyellow", // 23
    "brightyellow", // 24
    "allblack", // 25
    "redsmallpupil", // 26
    "devilblueblack", // 27
    "whitesmallpupil", // 28
    "glossedover", // 29
  ]